[package]
name = "constant"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.30"

[build-dependencies]
wit-component = "0.215"

[profile.release]
opt-level = "s"
lto = true
strip = true
