default:
    @just --list

build:
    cargo build --target wasm32-wasip2 --release

install: build
    mkdir -p ../bin
    cp target/wasm32-wasip2/release/constant.wasm ../bin/

test:
    cargo test

check:
    cargo check --target wasm32-wasip2

clean:
    cargo clean
