set shell := ["nu", "-c"]
set unstable

build component:
  just --justfile {{component}}/Justfile build

install component:
  just --justfile {{component}}/Justfile install

build-all:
  ls | where type == dir | get name | each { |component| just build $component }

install-all:
  ls | where type == dir | get name | each { |component| just install $component }
