[package]
name = "list-filter-regex-any"
version = "1.0.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.30"
regex = "1.10"

[profile.release]
opt-level = "s"
lto = true
strip = true
