build:
    cargo build --release --target wasm32-wasip2

test:
    cargo test

install: build
    mkdir -p ../../bin
    cp target/wasm32-wasip2/release/json_build_object.wasm ../../bin/

clean:
    cargo clean
