[package]
name = "string-concat"
version = "1.0.0"
edition = "2021"

# This is a standalone component, not part of the workspace
[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.30"

[profile.release]
opt-level = "s"
lto = true
strip = true
