[package]
name = "compare"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.30"

[profile.release]
opt-level = "s"
lto = true
strip = true

# Tell cargo this is not part of the workspace
[workspace]
